name: engine_simulator_launcher
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  engine_simulator_data:
    path: local_packages/engine_simulator_data
  settings_repository:
      path: local_packages/settings_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.17
  file_picker: ^5.2.5
  url_launcher: ^6.1.8

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
